[0m13:56:25.937873 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111dece50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111e0cfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111e0d850>]}


============================== 13:56:25.941955 | 20f2b617-4ff1-4f55-9d8c-96e6ef324db9 ==============================
[0m13:56:25.941955 [info ] [MainThread]: Running with dbt=1.5.7
[0m13:56:25.942521 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/tdyar/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m13:56:36.781237 [debug] [MainThread]: Starter project path: /opt/homebrew/anaconda3/envs/dbt_env/lib/python3.11/site-packages/dbt/include/starter_project
[0m13:56:42.847314 [info ] [MainThread]: No sample profile found for iris.
[0m13:56:42.847873 [info ] [MainThread]: 
Your new dbt project "walmartM5" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:56:42.848858 [debug] [MainThread]: Command `dbt init` succeeded at 13:56:42.848498 after 16.95 seconds
[0m13:56:42.849233 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111ded010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10de718d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10dfbaa90>]}
[0m13:56:42.849583 [debug] [MainThread]: Flushing usage events
[0m08:15:42.953415 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fab1a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10faca610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10facae50>]}


============================== 08:15:42.957702 | 3f0c12fa-3735-4e11-9270-0b323080365c ==============================
[0m08:15:42.957702 [info ] [MainThread]: Running with dbt=1.5.7
[0m08:15:42.958377 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/tdyar/workspace/isc-datafest/src/dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m08:15:42.959156 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tdyar/workspace/isc-datafest/src/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:15:42.960377 [debug] [MainThread]: Command `dbt build` failed at 08:15:42.959673 after 0.04 seconds
[0m08:15:42.960970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fad2f50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fad3dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bc62a10>]}
[0m08:15:42.961604 [debug] [MainThread]: Flushing usage events
[0m08:17:03.225929 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111efe710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f22050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f22890>]}


============================== 08:17:03.230051 | ff5a4ce5-d51f-42a7-9ac9-e99db68f1b9c ==============================
[0m08:17:03.230051 [info ] [MainThread]: Running with dbt=1.5.7
[0m08:17:03.230597 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/tdyar/workspace/isc-datafest/src/dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m08:17:03.231244 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tdyar/workspace/isc-datafest/src/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:17:03.232239 [debug] [MainThread]: Command `dbt build` failed at 08:17:03.231833 after 0.04 seconds
[0m08:17:03.232584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111efd910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e0c2a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111f2b690>]}
[0m08:17:03.232891 [debug] [MainThread]: Flushing usage events
